name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: sanely (JVM)
            cmd: sanely.jvm.test
          - name: sanely (Scala.js)
            cmd: sanely.js.test
          - name: compat (JVM)
            cmd: compat.jvm.test
          - name: compat (Scala.js)
            cmd: compat.js.test
          - name: sanely-jsoniter (JVM)
            cmd: sanely-jsoniter.jvm.test
          - name: sanely-jsoniter (Scala.js)
            cmd: sanely-jsoniter.js.test
    name: Test ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Test
        run: ./mill ${{ matrix.cmd }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Publish JVM
        run: ./mill sanely.jvm.publishSonatypeCentral
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}

      - name: Publish Scala.js
        run: ./mill sanely.js.publishSonatypeCentral
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}

      - name: Publish sanely-jsoniter JVM
        run: ./mill sanely-jsoniter.jvm.publishSonatypeCentral
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}

      - name: Publish sanely-jsoniter Scala.js
        run: ./mill sanely-jsoniter.js.publishSonatypeCentral
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
